import { categoryAnchor } from "./categorize.js";
import {
  chunkMarkdown,
  cleanMarkdownForChunking,
} from "./chunk-markdown.js";
import type { CrawledPage, PageCategory } from "./types.js";
import { CATEGORY_ORDER } from "./types.js";
import { hostnameFilename } from "./url.js";

function slugTitle(title: string): string {
  return title.replace(/^#+\s*/, "").trim() || "Untitled";
}

function demoteHeadings(markdown: string, pageTitle: string): string {
  const normalizedTitle = pageTitle.trim().toLowerCase();
  let body = markdown.trim();

  // Drop a leading H1 that duplicates the ### section title.
  const leading = /^(#{1,2})\s+(.+)\n+/.exec(body);
  if (leading && leading[2]!.trim().toLowerCase() === normalizedTitle) {
    body = body.slice(leading[0].length);
  }

  // Page bodies sit under ### so site H2 categories stay primary.
  return body
    .split("\n")
    .map((line) => {
      const match = /^(#{1,6})\s+(.*)$/.exec(line);
      if (!match) return line;
      const level = match[1]!.length;
      const next = Math.min(level + 2, 6);
      return `${"#".repeat(next)} ${match[2]}`;
    })
    .join("\n");
}

/** Clean, heading-split, and cap page bodies so the KB is RAG-ready. */
function optimizePageMarkdown(markdown: string, pageTitle: string): string {
  const cleaned = cleanMarkdownForChunking(markdown);
  const demoted = demoteHeadings(cleaned, pageTitle);
  const chunks = chunkMarkdown(demoted);
  if (chunks.length === 0) {
    return "";
  }
  return chunks.map((chunk) => chunk.content).join("\n\n");
}

export function assembleSiteMarkdown(params: {
  rootUrl: string;
  siteName: string;
  blurb: string | null;
  pages: CrawledPage[];
}): {
  markdown: string;
  categories: Array<{ name: PageCategory; count: number }>;
} {
  const { rootUrl, siteName, blurb, pages } = params;
  const byCategory = new Map<PageCategory, CrawledPage[]>();

  for (const category of CATEGORY_ORDER) {
    byCategory.set(category, []);
  }
  for (const page of pages) {
    byCategory.get(page.category)?.push(page);
  }

  const categories = CATEGORY_ORDER.map((name) => ({
    name,
    count: byCategory.get(name)?.length ?? 0,
  })).filter((c) => c.count > 0);

  const lines: string[] = [];
  lines.push(`# ${siteName}`);
  lines.push("");
  lines.push(`> Source: ${rootUrl}`);
  lines.push(
    `> Pages: ${pages.length} · Generated: ${new Date().toISOString()}`,
  );
  lines.push("");

  if (blurb) {
    lines.push(blurb);
    lines.push("");
  }

  lines.push("## Contents");
  lines.push("");
  for (const { name, count } of categories) {
    lines.push(
      `- [${name}](#${categoryAnchor(name)}) (${count} page${count === 1 ? "" : "s"})`,
    );
  }
  lines.push("");

  for (const { name } of categories) {
    const group = byCategory.get(name) ?? [];
    lines.push(`## ${name}`);
    lines.push("");

    for (const page of group) {
      const title = slugTitle(page.title);
      lines.push(`### ${title}`);
      lines.push("");
      lines.push(`Source: ${page.url}`);
      lines.push("");
      if (page.markdown.trim()) {
        const optimized = optimizePageMarkdown(page.markdown, title);
        lines.push(optimized || "_No extractable content._");
      } else {
        lines.push("_No extractable content._");
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push(
    `_Generated by Into markdown for agent knowledge bases. File: ${hostnameFilename(rootUrl)}_`,
  );
  lines.push("");

  return { markdown: lines.join("\n"), categories };
}
